# Timer Trigger configuration
intervalMin: 10
epcIntervalSec: 1
runFor: 2h
mode: 3
baseUrl: "http://localhost:9055"
epcList:
  - "E28011B0A502006D6D1E90F7"
  - "E28011B0A502006D6D1EF607"
  - "E28011B0A502006D6D1EF637"
# mode: 1
# singleEpc: "E28011B0A502006D6D1E90F7"
# singleEpcIndex: 0
deviceId: 1
devicePort: 0
durationSec: 60
qvalue: 0
rfmode: 113
connectTimeoutSec: 5
requestTimeoutSec: 30
shutdownWait: 30s
logDir: "logs"

# mode: 4
# scheduleSteps:
#   - devicePort: 0
#     epcList:
#       - "E28011B0A502006D6D1E90F7"
#   - devicePort: 1
#     epcList:
#       - "E28011B0A502006D6D1EF607"
#       - "E28011B0A502006D6D1EF637"
#   - devicePort: 2
#     epcList:
#       - "E28011B0A502006D6D1EF999"
