# Timer Trigger configuration
intervalMin: 10
runFor: 2h
mode: 5
baseUrl: "http://localhost:9055"
epcList:
  - "E28011B0A502006D6D1E90F7"
  - "E28011B0A502006D6D1EF607"
  - "E28011B0A502006D6D1EF637"
deviceId: 1
devicePort: 0
devicePortAlt: 1
durationSec: 60
qvalue: 0
rfmode: 113
connectTimeoutSec: 5
requestTimeoutSec: 30
shutdownWait: 30s
logDir: "logs"
